export const testUsers = [];

export const testAdminUsers = [];

export const testData = [
  {
    id: 1,
    name: 'Jane',
    parent_name: 'Mrs. Doe',
    contact: 'mrs.doe@gmail.com',
    gender: 'F',
    community: 'Belem',
    community_id: 1,
    country: 'Brazil',
    country_id: 1,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 2,
    name: 'Jose',
    parent_name: 'Mr. Machado',
    contact: 'machado@email.com',
    gender: 'M',
    community: 'Belem',
    community_id: 1,
    country: 'Brazil',
    country_id: 1,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 3,
    name: 'Paulo',
    parent_name: 'Ms. Moreno',
    contact: 'moreno@email.com',
    gender: 'M',
    community: 'Fortaleza',
    community_id: 2,
    country: 'Brazil',
    country_id: 1,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 4,
    name: 'Joao',
    parent_name: 'Mr. Antunes',
    contact: 'antunes@email.com',
    gender: 'M',
    community: 'Fortaleza',
    community_id: 2,
    country: 'Brazil',
    country_id: 1,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 5,
    name: 'Amanda',
    parent_name: 'Ms. Andrade',
    contact: 'andrade@email.com',
    gender: 'F',
    community: 'Manaus',
    community_id: 3,
    country: 'Brazil',
    country_id: 1,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 6,
    name: 'Yessica',
    parent_name: 'Mr. Nunez',
    contact: 'nunez@email.com',
    gender: 'F',
    community: 'Manaus',
    community_id: 3,
    country: 'Brazil',
    country_id: 1,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 7,
    name: 'Gabrela',
    parent_name: 'Mrs. Rodriquez',
    contact: 'rodriquez@email.com',
    gender: 'F',
    community: 'Sucre',
    community_id: 4,
    country: 'Bolivia',
    country_id: 2,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 8,
    name: 'Erika',
    parent_name: 'Mr. Dipierri',
    contact: 'dipierri@email.com',
    gender: 'F',
    community: 'Sucre',
    community_id: 4,
    country: 'Bolivia',
    country_id: 2,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 9,
    name: 'Sergio',
    parent_name: 'Mrs. Alfaro',
    contact: 'alfaro@email.com',
    gender: 'M',
    community: 'Trinidad',
    community_id: 5,
    country: 'Bolivia',
    country_id: 2,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 10,
    name: 'Ronaldino',
    parent_name: 'Mr. Gomez',
    contact: 'gomez@email.com',
    gender: 'M',
    community: 'Trinidad',
    community_id: 5,
    country: 'Bolivia',
    country_id: 2,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 11,
    name: 'Aliz',
    parent_name: 'Mrs. Scapoli',
    contact: 'scapoli@email.com',
    gender: 'F',
    community: 'El Torno',
    community_id: 6,
    country: 'Bolivia',
    country_id: 2,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 12,
    name: 'Alejandro',
    parent_name: 'Mr. Mamolini',
    contact: 'mamolini@email.com',
    gender: 'M',
    community: 'El Torno',
    community_id: 6,
    country: 'Bolivia',
    country_id: 2,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 13,
    name: 'Mrs. Salvatori',
    parent_name: 'Ms. Moreno',
    contact: 'salvatori@email.com',
    gender: 'F',
    community: 'Krassang',
    community_id: 7,
    country: 'Cambodia',
    country_id: 3,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 14,
    name: 'Paulo',
    parent_name: 'Mr. Gaathaa',
    contact: 'gaathaa@email.com',
    gender: 'M',
    community: 'Krassang',
    community_id: 2,
    country: 'Cambodia',
    country_id: 3,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 15,
    name: 'Devi',
    parent_name: 'Mrs. Teteny',
    contact: 'teteny@email.com',
    gender: 'F',
    community: 'Memot',
    community_id: 8,
    country: 'Cambodia',
    country_id: 3,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 16,
    name: 'Pich',
    parent_name: 'Mr. Cho',
    contact: 'moreno@email.com',
    gender: 'F',
    community: 'Memot',
    community_id: 8,
    country: 'Cambodia',
    country_id: 3,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 17,
    name: 'Poeu',
    parent_name: 'Mrs. Talin',
    contact: 'talin@email.com',
    gender: 'M',
    community: 'Samraong',
    community_id: 9,
    country: 'Cambodia',
    country_id: 3,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
  {
    id: 18,
    name: 'Gaadhi',
    parent_name: 'Mr. Baadal',
    contact: 'baadal@email.com',
    gender: 'M',
    community: 'Samraong',
    community_id: 9,
    country: 'Cambodia',
    country_id: 3,
    dob: '09/28/2010',
    screenings: [
      {
        date: '11/11/17',
        weight: 9,
        height: 43,
      },
      {
        date: '5/11/18',
        weight: 10,
        height: 44,
      },
      {
        date: '11/11/18',
        weight: 11,
        height: 56,
      },
      {
        date: '5/11/19',
        weight: 13,
        height: 72,
      },
    ],
  },
];
